"""
Agent 5 — Publisher
Input : product_name, reformulation_date, classified_reviews, inflection
Output: { "cited_url": str, "senso_document_id": str }

On inflection detected:
  1. Builds a sourced markdown alert from ClassifiedReview[]
  2. Ingests it into Senso as a knowledge document
  3. Queries Senso to generate a cited summary (the public artifact)
  4. Returns the Senso document URL as cited_url
"""

import os
import json
import requests
from datetime import datetime

SENSO_API_KEY = os.environ["SENSO_API_KEY"]
SENSO_BASE_URL = "https://apiv2.senso.ai"

HEADERS = {
    "Authorization": f"Bearer {SENSO_API_KEY}",
    "Content-Type": "application/json",
}


# ── 1. Build the markdown alert ───────────────────────────────────────────────

def _build_alert_markdown(
    product_name: str,
    reformulation_date: str,
    classified_reviews: list[dict],
    inflection: dict,
) -> str:
    """Render a sourced markdown alert from classified reviews."""

    # Filter to complaint reviews only
    complaints = [
        r for r in classified_reviews
        if r.get("complaint_category", "none") != "none"
    ]

    # Group by category
    by_category: dict[str, list] = {}
    for r in complaints:
        cat = r["complaint_category"]
        by_category.setdefault(cat, []).append(r)

    lines = [
        f"# Reformulation Alert: {product_name}",
        f"",
        f"**Reformulation date:** {reformulation_date}",
        f"**Inflection week:** {inflection.get('inflection_week', 'unknown')}",
        f"**Severity score:** {inflection.get('severity', 0):.1f}x baseline",
        f"**Total complaints detected:** {len(complaints)}",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        f"",
        f"---",
        f"",
        f"## Summary",
        f"",
        f"Complaint volume spiked in the week of "
        f"**{inflection.get('inflection_week', 'unknown')}**, "
        f"{inflection.get('severity', 0):.1f}x above the pre-reformulation baseline. "
        f"The dominant complaint category is "
        f"**{max(by_category, key=lambda c: len(by_category[c])) if by_category else 'unknown'}**.",
        f"",
        f"---",
        f"",
        f"## Complaints by Category",
        f"",
    ]

    for category, reviews in by_category.items():
        lines.append(f"### {category.capitalize()} ({len(reviews)} complaints)")
        lines.append("")
        for r in reviews[:5]:  # cap at 5 per category for readability
            excerpt = r.get("raw_excerpt", "").strip()
            url = r.get("url", "")
            date = r.get("published_date", "")
            trace = " | ".join(r.get("rule_trace", []))
            lines.append(f"- **[{date}]** {excerpt[:150]}...")
            lines.append(f"  - Source: {url}")
            lines.append(f"  - Rule: `{trace}`")
            lines.append("")

    lines += [
        "---",
        "",
        "## Methodology",
        "",
        "Reviews retrieved via Tavily live web search across Reddit, Amazon, and retailer sites. "
        "Classification performed by Prometheux using declarative Vadalog rules — "
        "each complaint is linked to the exact rule and lexical marker that triggered it. "
        "Aggregation and inflection detection via ClickHouse week×category bucketing.",
        "",
        "*Generated by Reformulation Sentinel — autonomous CPG complaint monitoring*",
    ]

    return "\n".join(lines)


# ── 2. Ingest into Senso ──────────────────────────────────────────────────────

def _ingest_to_senso(title: str, markdown_content: str) -> str:
    """
    Upload the alert as a raw text source to Senso.
    Returns the document/content ID.
    """
    url = f"{SENSO_BASE_URL}/content"
    payload = {
        "title": title,
        "content": markdown_content,
        "content_type": "markdown",
        "tags": ["reformulation-sentinel", "alert", "cpg"],
    }

    resp = requests.post(url, headers=HEADERS, json=payload, timeout=30)

    if resp.status_code not in (200, 201):
        # Try alternate endpoint shape
        payload2 = {
            "title": title,
            "body": markdown_content,
            "type": "document",
        }
        resp = requests.post(url, headers=HEADERS, json=payload2, timeout=30)

    resp.raise_for_status()
    data = resp.json()

    # Extract ID from response — Senso returns { id, url, ... } or nested data
    doc_id = (
        data.get("id")
        or data.get("data", {}).get("id")
        or data.get("content_id")
        or "unknown"
    )
    print(f"[publisher] Ingested to Senso, document id: {doc_id}")
    return str(doc_id)


# ── 3. Generate cited summary via Senso ──────────────────────────────────────

def _generate_cited_summary(product_name: str, doc_id: str) -> str:
    """
    Ask Senso to generate a cited answer from the ingested document.
    Returns the public URL of the generated content or a senso search URL.
    """
    url = f"{SENSO_BASE_URL}/generate"
    payload = {
        "query": (
            f"Summarise the reformulation complaint alert for {product_name}. "
            f"Include the inflection date, dominant complaint category, "
            f"and cite the source reviews."
        ),
        "source_ids": [doc_id],
        "format": "markdown",
    }

    try:
        resp = requests.post(url, headers=HEADERS, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()

        # Try to extract a public URL from the response
        cited_url = (
            data.get("url")
            or data.get("data", {}).get("url")
            or data.get("public_url")
            or f"https://apiv2.senso.ai/content/{doc_id}"
        )
        return cited_url

    except Exception as e:
        print(f"[publisher] Generate step failed ({e}), falling back to content URL")
        return f"https://apiv2.senso.ai/content/{doc_id}"


# ── 4. Main publish function ──────────────────────────────────────────────────

def publish_alert(
    product_name: str,
    reformulation_date: str,
    classified_reviews: list[dict],
    inflection: dict,
) -> dict:
    """
    Full publish pipeline:
      build markdown → ingest to Senso → generate cited output → return URL
    """
    print(f"[publisher] Building alert for '{product_name}'...")

    title = (
        f"Reformulation Alert: {product_name} — "
        f"Spike week {inflection.get('inflection_week', 'unknown')}"
    )
    markdown = _build_alert_markdown(
        product_name, reformulation_date, classified_reviews, inflection
    )

    print(f"[publisher] Ingesting to Senso ({len(markdown)} chars)...")
    doc_id = _ingest_to_senso(title, markdown)

    print(f"[publisher] Generating cited summary...")
    cited_url = _generate_cited_summary(product_name, doc_id)

    print(f"[publisher] Done → {cited_url}")
    return {
        "cited_url": cited_url,
        "senso_document_id": doc_id,
    }


# ── Stub for offline dev ──────────────────────────────────────────────────────

def publish_alert_stub(
    product_name: str,
    reformulation_date: str,
    classified_reviews: list[dict],
    inflection: dict,
) -> dict:
    """Returns a fake URL — use until Senso key is confirmed working."""
    print("[publisher] STUB MODE — not calling Senso")
    return {
        "cited_url": f"https://apiv2.senso.ai/alerts/{product_name.lower().replace(' ', '-')}-stub",
        "senso_document_id": "stub-id-000",
    }


if __name__ == "__main__":
    # Smoke test with stub
    sample_inflection = {
        "inflection_week": "2017-01-09",
        "reformulation_date": "2017-01-01",
        "severity": 3.2,
    }
    sample_reviews = [
        {
            "url": "https://reddit.com/r/chocolate/1",
            "variant_id": "cdm_post_2017",
            "complaint_category": "taste",
            "published_date": "2017-06-15",
            "rule_trace": ["RULE:taste_signal+post_reformulation — matched 'changed the recipe'"],
            "raw_excerpt": "They changed the recipe and now it tastes completely different.",
        }
    ]
    result = publish_alert_stub(
        "Cadbury Dairy Milk", "2017-01-01", sample_reviews, sample_inflection
    )
    print(json.dumps(result, indent=2))
