import { RunResult } from "@/lib/types";
import { mockRun } from "@/lib/mockData";

export const dynamic = "force-dynamic";

const ORCHESTRATOR = process.env.ORCHESTRATOR_URL ?? "http://localhost:8000";
const MONTHS = ["", "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];

function prettyDate(iso?: string | null) {
  if (!iso) return "unknown";
  const [y, m, d] = iso.split("-");
  return `${MONTHS[parseInt(m, 10)]?.slice(0, 3)} ${parseInt(d, 10)}, ${y}`;
}

async function getData(product: string): Promise<RunResult> {
  try {
    const r = await fetch(`${ORCHESTRATOR}/run?product=${encodeURIComponent(product)}`, {
      cache: "no-store",
      signal: AbortSignal.timeout(90_000),
    });
    if (!r.ok) throw new Error(`orchestrator ${r.status}`);
    return await r.json();
  } catch {
    return { ...mockRun, product };
  }
}

function buildMarkdown(d: RunResult): string {
  const complaints = d.reviews.filter((r) => r.complaint_category !== "none");
  const sev = d.inflection ? Math.round(d.inflection.severity) : 0;
  const byCat: Record<string, typeof complaints> = {};
  for (const r of complaints) (byCat[r.complaint_category] ??= []).push(r);

  const lines: string[] = [
    `# Reformulation Alert: ${d.product}`,
    ``,
    `**Reformulation date:** ${prettyDate(d.reformulation_date)}`,
    `**Inflection week:** ${prettyDate(d.inflection?.inflection_week)}`,
    `**Severity:** ${sev}x baseline`,
    `**Cited complaints:** ${complaints.length}`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    `Complaint volume rose ${sev}x above the pre-reformulation baseline, peaking the ` +
      `week of ${prettyDate(d.inflection?.inflection_week)}.`,
    ``,
    `## Cited complaints`,
    ``,
  ];

  for (const [cat, rows] of Object.entries(byCat)) {
    lines.push(`### ${cat[0].toUpperCase() + cat.slice(1)} (${rows.length})`, ``);
    for (const r of rows) {
      const rule = r.rule_trace?.length ? r.rule_trace[r.rule_trace.length - 1].replace(/^→\s*/, "") : "";
      lines.push(`- **[${prettyDate(r.published_date)}]** "${r.raw_excerpt}"`);
      lines.push(`  - Source: ${r.url}`);
      if (rule) lines.push(`  - Rule: \`${rule}\``);
      lines.push(``);
    }
  }

  lines.push(
    `---`,
    ``,
    `*Generated by Reformulation Sentinel. Mentions via Tavily live search, classified by ` +
      `Prometheux declarative rules, aggregated and spike-detected in ClickHouse.*`
  );
  return lines.join("\n");
}

export async function GET(
  _req: Request,
  { params }: { params: { slug: string } }
) {
  const url = new URL(_req.url);
  const product = url.searchParams.get("p")
    ? decodeURIComponent(url.searchParams.get("p")!)
    : params.slug.replace(/-/g, " ");
  const data = await getData(product);
  return new Response(buildMarkdown(data), {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `inline; filename="${params.slug}-alert.md"`,
    },
  });
}
